POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvaW5lblRlc3RhYWphIiwiaWQiOiI1ZjJiOTRmZDk4NDFiNjJiMzg2MjZmZWQiLCJpYXQiOjE1OTY2OTI4NDh9.Gcvw3BO6JYFIkvC4NdygEQfnyy5UTRmbP4WCYRuormo

{
    "url": "http://joku.com",
    "title": "Suomalaisen aikuisviihteen kehitys",
    "author": "Osku",
    "likes": 666
}